# Основные настройки
title: "Mas Hakim B.O.S.H"
description: "Bali Open Sources Hub | Terminal Root"
baseurl: "" 
url: "https://mas-hakim.github.io"

# ТЕМА (Hacker — это максимально близкий к UNIX/Terminal стиль)
theme: jekyll-theme-hacker

# Навигация (в этой теме ссылки появятся в шапке автоматически)
header_pages:
  - index.md
  - about.md
  - posts.md
  - places.md
  - contacts.md

# Плагины (только те, что разрешены GitHub в safe-mode)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Настройки парсера
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
